theme = "mytheme"

[editor]
line-number = "relative"
mouse = false
end-of-line-diagnostics = "hint"
completion-timeout = 5
rulers = [120]

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 500

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

[keys.normal]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-r = [
    ":write-all",
    ":insert-output scooter --no-stdin >/dev/tty",
    ":redraw",
    ":reload-all"
]

[keys.normal.space]
A-L = [":toggle-option line-number relative absolute"]
A-R = [":toggle-option rulers [] [120]"]

# Replace built-in explorer with yazi
e = [
  ':sh rm -f /tmp/unique-file-h21a434',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file-h21a434',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file-h21a434}',
  ':redraw',
]

# --- git
[keys.normal.space.g]
# Launch lazygit
l = [
  ":write-all",
  ":insert-output lazygit >/dev/tty",
  ":reload-all",
  ":redraw",
]

# Inline git blame
b = ":sh git log -n 5 --format='format:%%h (%%an: %%ar) %%s' --no-patch -L%{cursor_line},+1:%{buffer_name}"
y = ":sh git log -n 1 --format='format:%%h' --no-patch -L%{cursor_line},+1:%{buffer_name} | pbcopy"
p = "changed_file_picker"
r = ":reset-diff-change"

# --- Buffer
[keys.normal.space.b]
p = "buffer_picker"
c = ":buffer-close"
o = ":buffer-close-others"

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode


