[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.target = "wasm32-unknown-unknown"

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.swiftlint]
command = "swiftlint"

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "harper-ls"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "bun eslint", args = ["--fix"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "mdformat", args = ["-", "--wrap", "120"] }
