[language-server.rust-analyzer.config]
check.command = "clippy"
cargo.target = "wasm32-unknown-unknown"

[language-server.kotlin-language-server]
command = "bash"
args = [
  "-lc",
  "JAVA_HOME=$(brew --prefix openjdk@21)/libexec/openjdk.jdk/Contents/Home kotlin-language-server"
]

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.swiftlint]
command = "swiftlint"

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "harper-ls"]
formatter = { command = "rustfmt", args = ["+nightly", "--emit", "stdout"], cwd = "workspace" }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "bun eslint", args = ["--fix"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "mdformat", args = ["-", "--wrap", "120"] }
